version: 0.2

phases:
  build:
    commands:
      - mvn clean package -Ddockerfile.skip -Dmaven.test.skip=true
artifacts:
  files:
    - target/sldownloader.jar
    - Dockerfile
    - docker-compose.yml
    - nginx.tmpl