version: 0.2

phases:
  build:
    commands:
      - mvn clean package -Ddockerfile.skip -Dmaven.test.skip=true
artifacts:
  files:
    - code_deploy_scripts/start_app.sh
    - code_deploy_scripts/stop_app.sh
    - appspec.yml
    - target/sldownloader.jar
    - Dockerfile
    - docker-compose.yml
    - nginx.tmpl