version: '3'

services:
  sldownloader:
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8080:8080/tcp"
    volumes:
      - './database:/var/lib/apps/sldownloader/database'
      - './logs:/var/log/sldownloader'
    mem_limit: 512m
