version: '2'

services:
  sldownloader:
    image: 535425158818.dkr.ecr.ap-southeast-1.amazonaws.com/crabranch/sldownloader:latest
    environment:
      - VIRTUAL_HOST=crabranch.info
      - LETSENCRYPT_HOST=crabranch.info
      - LETSENCRYPT_EMAIL=james.villegas@gmail.com
      - SPRING_PROFILES_ACTIVE
    expose:
      - "8080"
    volumes:
      - sldownloader-database:/var/lib/apps/sldownloader/database
    mem_limit: 400m

volumes:
  sldownloader-database:
    driver: local

networks:
  default:
    external:
      name: crabranch_network
