version: '2'

services:
  nginx:
    image: nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /certs:/etc/nginx/certs:ro

  nginxdockergen:
    image: jwilder/docker-gen
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  nginxletsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /certs:/etc/nginx/certs:rw

  sldownloader:
    image: 535425158818.dkr.ecr.ap-southeast-1.amazonaws.com/crabranch/sldownloader:latest
    environment:
      - VIRTUAL_HOST=crabranch.info
      - LETSENCRYPT_HOST=crabranch.info
      - LETSENCRYPT_EMAIL=james.villegas@gmail.com
      - SPRING_PROFILES_ACTIVE
    expose:
      - "8080"
    volumes:
      - sldownloader-database:/var/lib/apps/sldownloader/database

volumes:
  sldownloader-database:
    driver: local